version: '3.6'
services:
  traefik:
    image: "traefik:v2.11"
    container_name: "traefik"
    command: --api.insecure=true --providers.docker.network=traefik
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - traefik_network

networks:
  traefik_network:
    external: true
