version: '3.6'

services:
  gitlab:
    image: gitlab/gitlab-ee:16.7.7-ee.0
    container_name: gitlab
    ports:
      - '82:80'
      - '443:443'
      - '23:22'
    volumes:
      - './config:/etc/gitlab'
      - './logs:/var/log/gitlab'
      - './data:/var/opt/gitlab'
    labels:
      - "traefik.http.routers.whoami.rule=Host(`gitlab.example`)"
