version: '3.6'
services:
  wireguard:
    image: linuxserver/wireguard:v1.0.20210914-ls4
    container_name: wireguard
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Paris
      - PEERS=1
      - SERVERURL=auto
      - PEERDNS=auto
      - INTERNAL_SUBNET=10.13.13.0
    volumes:
      - ./config:/config
      - /lib/modules:/lib/modules
    ports:
      - 51820:51820/udp
      - 51821:5000/tcp
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
